import type { AgencyKind } from "@tjob/shared";

export type SuggestedAgency = {
  name: string;
  kind: AgencyKind;
  focus: string;
  area: string;
  address: string;
  website: string;
  applyUrl: string;
  email: string;
  phone: string;
  linkedinUrl: string;
  howToApproach: string;
};

/** When the details below were last checked against each firm's own website. */
export const SUGGESTIONS_CHECKED_ON = "8 Oct 2026";

/** Bengaluru recruitment agencies and hiring platforms for Java / Node.js developer roles. */
export const SUGGESTED_AGENCIES: SuggestedAgency[] = [
  {
    name: "TeamLease Digital",
    kind: "staffing",
    focus: "Specialised talent solutions arm of the TeamLease group, focused on tech staffing (staff augmentation and contract roles); its job board lists software engineering openings.",
    area: "Koramangala",
    address: "No 77, 315 Work Avenue Campus, Ascent Building, Jyoti Nivas College Rd, Koramangala Industrial Layout, Bengaluru, Karnataka. PIN - 560 095",
    website: "https://www.teamleasedigital.com/",
    applyUrl: "https://www.teamleasedigital.com/jobsearch",
    email: "",
    phone: "080-6824-3000",
    linkedinUrl: "https://www.linkedin.com/company/teamleasedigital/",
    howToApproach: "Register on the TeamLease Digital portal, upload your CV (doc/docx/rtf/pdf, max 2 MB), then filter the job search by Bangalore and Java/Node.js and apply to individual openings. Expect contract or contract-to-hire offers from recruiters who call you after you apply. The only email on the contact page is a marketing address, so don't send your CV there.",
  },
  {
    name: "Quess Corp (Quess IT Staffing)",
    kind: "staffing",
    focus: "Bengaluru-headquartered staffing group whose IT staff-augmentation business supplies contract IT professionals to clients, with 350+ in-house IT recruiters.",
    area: "Hosur Road, Bommanahalli",
    address: "Quess Tower, Sky Walk Avenue, 32/4, Hosur Road, Roopena Agrahara, Bommanahalli, Bangalore South, Karnataka, India, 560068",
    website: "https://www.quesscorp.com/",
    applyUrl: "",
    email: "",
    phone: "1800-572-3333",
    linkedinUrl: "https://www.linkedin.com/company/quess-corp/",
    howToApproach: "Quess IT Staffing recruiters mostly find candidates through job boards and LinkedIn, so keep your Naukri, foundit and LinkedIn profiles current with Java/Node.js keywords. When a Quess recruiter contacts you about a contract-to-hire role, respond. The careers portal on quesscorp.com mostly lists Quess's own internal roles, and the old quessitstaffing.com domain is now parked.",
  },
  {
    name: "Randstad India",
    kind: "staffing",
    focus: "Global staffing and recruitment firm whose Bengaluru office recruits across sectors including IT, for both permanent and staffing roles.",
    area: "Main Guard Cross Road",
    address: "Randstad India Private Limited, Randstad Tower, No.1, Main Guard Cross Road, Bengaluru 560001 KA India",
    website: "https://www.randstad.in/",
    applyUrl: "https://www.randstad.in/jobs/",
    email: "",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/randstad-india/",
    howToApproach: "Search randstad.in/jobs for Java and Node.js developer roles in Bengaluru and apply directly. Also send your CV through the 'submit CV' form linked on the Bengaluru office page. The emails published on the site are for sales enquiries and associate PF queries, not CVs.",
  },
  {
    name: "Adecco India",
    kind: "staffing",
    focus: "Global staffing firm with a Bengaluru office; its India job board has an IT category, and you can register your CV there.",
    area: "Mahadevapura (ITPL Main Road)",
    address: "13th Floor, Summit - B, Brigade Metropolis, Garudachar Palya, Mahadevapura, ITPL Main Road, Bengaluru, Karnataka, 560048",
    website: "https://www.adecco.com/en-in",
    applyUrl: "https://www.adecco.com/en-in/job-seeker?CategoryFilter=ADCINCAT014",
    email: "",
    phone: "08068407399",
    linkedinUrl: "https://www.linkedin.com/company/adecco",
    howToApproach: "Browse the IT category on Adecco India's job-seeker page and apply to Bengaluru developer roles. Also use the 'Submit your CV' registration form on the site so recruiters can match you to future openings. The LinkedIn link on the site goes to Adecco's global page, not an India-specific one.",
  },
  {
    name: "Experis India (ManpowerGroup)",
    kind: "staffing",
    focus: "ManpowerGroup's IT brand in India (Experis IT Pvt. Ltd.), covering IT staffing augmentation, permanent recruitment and project solutions, with a Bengaluru branch and offshore centre.",
    area: "Bannerghatta Road",
    address: "Experis IT Pvt. Ltd. 7th Floor, Tower C, IBC Knowledge Park, Bannerghatta Road, Bangalore - 560029, Karnataka, India",
    website: "https://www.experisindia.com/",
    applyUrl: "https://careers.experisindia.com/jobs",
    email: "resume@manpowergroup.com",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/experis-it-pvt-ltd-/",
    howToApproach: "Apply to Java and Node.js openings on the Experis careers portal and join its talent community. You can also email your CV to resume@manpowergroup.com, which ManpowerGroup India's contact page lists for job opportunities. The published toll-free numbers are for business enquiries and current associates, not new candidates.",
  },
  {
    name: "Xpheno",
    kind: "staffing",
    focus: "Bengaluru-headquartered specialist staffing firm offering IT staffing (contract and contract-to-hire) plus direct IT hiring for GCCs and enterprises.",
    area: "Residency Road, Richmond Town",
    address: "Beginest Harbor 6, No.76, 3rd Cross Road, Residency Road, Ashok Nagar, Richmond Town, Bengaluru, KA (INDIA). Pin Code: 560025.",
    website: "https://www.xpheno.com/",
    applyUrl: "",
    email: "hr@xpheno.com",
    phone: "+91 98453 31138",
    linkedinUrl: "https://www.linkedin.com/company/xpheno/",
    howToApproach: "Xpheno has no candidate job board on its site (its /careers page is for jobs at Xpheno itself), so follow its LinkedIn page and apply to the client IT openings its recruiters post there. You can also email a short note and your CV to hr@xpheno.com, the HR address on its contact page.",
  },
  {
    name: "CIEL HR",
    kind: "staffing",
    focus: "HR services firm with its main office in Bengaluru; its IT staffing practice places software developers on temporary, contract-to-hire and permanent terms.",
    area: "HSR Layout",
    address: "CIEL HR Services Ltd #2802 (Broadway Building),2nd & 3rd Floor, 27th Main Road,HSR Layout, Sector 1,Bengaluru 560102",
    website: "https://www.cielhr.com/",
    applyUrl: "https://www.cielhr.com/jobs/bangalore",
    email: "Info@cielhr.com",
    phone: "+91 7816 000 111",
    linkedinUrl: "https://in.linkedin.com/company/cielhr",
    howToApproach: "Use the CIEL HR jobs portal (Bangalore page) to search Java and Node.js roles, then submit your resume against specific openings. The site states that CIEL HR never charges candidates any fees, so treat anyone asking for money in its name as a scam.",
  },
  {
    name: "Careernet",
    kind: "recruiter",
    focus: "Bengaluru-based talent acquisition firm offering permanent hiring, professional staffing and leadership hiring; it sends candidates to its MyCareernet job platform.",
    area: "Outer Ring Road, Devarabisanahalli",
    address: "Careernet Campus, Plot No. 53, Kariyammana Agrahara Road, Devarabisana Halli (Next to Intel Junction Flyover), Outer Ring Road, Bangalore, Karnataka - 560103",
    website: "https://www.careernet.in/",
    applyUrl: "https://mycareernet.co/",
    email: "",
    phone: "+91-80-66560000",
    linkedinUrl: "https://www.linkedin.com/company/careernet-consulting",
    howToApproach: "Create a profile on MyCareernet, which Careernet's site points job seekers to (mycareernet.in now redirects to mycareernet.co). Apply to Java and Node.js roles and hiring challenges there. The only email on the contact page is a sales address, so use the platform instead.",
  },
  {
    name: "Michael Page India",
    kind: "recruiter",
    focus: "Professional recruitment consultancy, mainly mid-to-senior level, with a Technology practice and tech contracting jobs; has a Bengaluru office.",
    area: "Domlur (Embassy Golf Links)",
    address: "1st Floor, A block, Sunriver Building, Embassy Golf Links Business Park, Domlur Bengaluru 560071 Karnataka India",
    website: "https://www.michaelpage.co.in/",
    applyUrl: "https://www.michaelpage.co.in/jobs/technology",
    email: "enquiries@michaelpage.co.in",
    phone: "080 6826 6800",
    linkedinUrl: "https://www.linkedin.com/company/michael-page",
    howToApproach: "Apply to specific Bengaluru roles in the Technology jobs section, and use 'Submit your CV' to create a profile so consultants can find you for other roles. Its roles skew mid-to-senior, so it fits best once you have several years of backend experience. The LinkedIn link on the site goes to Michael Page's global page.",
  },
  {
    name: "Zyoin Group",
    kind: "recruiter",
    focus: "Bengaluru-based tech recruitment and talent advisory firm hiring software engineers for IT services, product companies, startups and GCCs.",
    area: "HSR Layout",
    address: "UrbanVault 6/A-1, 4th floor, 18th Cross Rd, HSR Layout, Bengaluru, Karnataka 560102",
    website: "https://www.zyoin.com/",
    applyUrl: "https://www.linkedin.com/company/zyoin/jobs/",
    email: "info@zyoin.com",
    phone: "7090811000",
    linkedinUrl: "https://www.linkedin.com/company/zyoin/",
    howToApproach: "Zyoin's website sends job seekers to its LinkedIn Jobs tab, so follow the company and apply there to Java and Node.js roles at its client companies. You can also connect with its tech recruiters directly on LinkedIn.",
  },
  {
    name: "Collabera",
    kind: "staffing",
    focus: "Global IT staffing and talent solutions firm with a Bengaluru office; supplies IT talent in India, including for GCCs.",
    area: "Outer Ring Road, Doddanakundi",
    address: "\"ROACH ICON\", Unit No. 9, Mezzanine Floor, Doddanakundi Village, Next to Akme Ballet, K.R. Puram Hobli, Outer Ring Road, Bangalore – 560 037",
    website: "https://www.collabera.com/",
    applyUrl: "https://www.collabera.com/submit-resume/",
    email: "info@collabera.com",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/collabera/",
    howToApproach: "Submit your resume through Collabera's form with India as your country, then check its job search for Bangalore openings. India listings weren't visible when this was checked, so treat it as a secondary channel and respond if a Collabera recruiter contacts you.",
  },
  {
    name: "PeopleLogic Business Solutions",
    kind: "recruiter",
    focus: "Bengaluru-based recruitment firm (founded 2007) doing technology talent acquisition, contract staffing and RPO for IT companies, GCCs and startups.",
    area: "C V Raman Nagar",
    address: "1st Floor, Wings of Eagles, S.S Commercial Estate, Nagavarapalya, C V Raman Nagar, Bengaluru, Karnataka 560093.",
    website: "https://peoplelogic.in/",
    applyUrl: "https://peoplelogic.in/work-with-our-clients/",
    email: "contact@peoplelogic.in",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/peoplelogic-business-solutions/",
    howToApproach: "Browse client openings on the 'Work with our clients' page and apply to Java and Node.js roles. The page embeds an Oorwin careers board, so open it in a full browser. For general queries, use the contact form, or the contact@peoplelogic.in address listed in the site's company details.",
  },
  {
    name: "TEKsystems India",
    kind: "staffing",
    focus: "Allegis Group's IT staffing and services firm; in India it places IT consultants with client companies and also hires full-time for its own Global Services delivery centres. Three Bengaluru offices.",
    area: "Bannerghatta Road (NS Palya)",
    address: "193, Commerce @Mantri, Bannerghatta Road Level 2, 3, 4 No. 12/1 & 12/2, NS Palya, Bengaluru, Karnataka 560076",
    website: "https://www.teksystems.com/en-in",
    applyUrl: "https://jobs.en-in.teksystems.com/",
    email: "",
    phone: "+91 80 4610 8002",
    linkedinUrl: "",
    howToApproach: "Search the India job portal for Java and Node.js roles in Bengaluru and create a profile when you apply. Its careers page splits jobs into consultant roles at client companies ('Work with us') and full-time roles at TEKsystems Global Services ('Work for us'), so check which one a listing is. The phone number is the main Bannerghatta Road office.",
  },
  {
    name: "Multi Recruit",
    kind: "recruiter",
    focus: "Bengaluru-based recruitment consultancy with an IT practice covering web, full-stack and mobile development, cloud and data roles.",
    area: "Bull Temple Road",
    address: "#103, 2nd Floor, Bull Temple Road, Bangalore - 560019",
    website: "https://www.multirecruit.com/",
    applyUrl: "https://jobs.multirecruit.com/",
    email: "info@multirecruit.com",
    phone: "+91 8880424000",
    linkedinUrl: "https://www.linkedin.com/company/multi-recruit",
    howToApproach: "Search its job board for Bengaluru developer roles and apply to specific openings. The site states that all its services for job seekers are free of cost. info@multirecruit.com is its only published email, so use it for a short note with your CV only if no listing fits.",
  },
  {
    name: "White Horse Manpower",
    kind: "recruiter",
    focus: "Bengaluru-headquartered recruitment firm (since 2007) with an IT & Technology practice covering software, cloud, data and testing roles, alongside a large non-IT business.",
    area: "",
    address: "",
    website: "https://www.whitehorsemanpower.in/",
    applyUrl: "",
    email: "",
    phone: "+91 85532 81835",
    linkedinUrl: "",
    howToApproach: "Call the IT jobs number on its website (it has a separate non-IT line) and ask for Java or Node.js developer openings in Bengaluru. Many of its listings on other job boards are BPO and voice-process roles, so ask specifically for software roles. The site states recruitment is 100% free for job seekers, so don't pay anyone who asks for money in its name.",
  },
  {
    name: "Talentiser",
    kind: "recruiter",
    focus: "Recruitment firm hiring for tech, SaaS and product companies and startups, including software engineering and AI/ML roles; it has a Bengaluru office in Koramangala.",
    area: "Koramangala",
    address: "We Work, Prestige Atlanta, 80 Feet Rd, Koramangala 1A Block, Bengaluru, Karnataka 560034",
    website: "https://www.talentiser.com/",
    applyUrl: "",
    email: "",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/talentiser/",
    howToApproach: "Its website's jobs page lists mostly Talentiser's own recruiter roles, not client openings, so follow its LinkedIn page for client job posts and connect with its tech recruiters there. Send a short note with your stack (Java/Spring Boot or Node.js), years of experience and notice period.",
  },
  {
    name: "Instahyre",
    kind: "platform",
    focus: "Hiring platform where you build a profile and get matched to roles, and companies send you interview interest; heavy on product companies and startups.",
    area: "",
    address: "",
    website: "https://www.instahyre.com/",
    applyUrl: "https://www.instahyre.com/candidates/register/",
    email: "",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/instahyre",
    howToApproach: "Sign up and upload your latest resume. Instahyre matches you to relevant roles and companies send interview interest, which you can accept or ignore. You can also limit which companies see your profile and apply selectively.",
  },
  {
    name: "Cutshort",
    kind: "platform",
    focus: "AI-matched tech job platform popular with product engineers and startups; you upload a resume and companies invite you to interview.",
    area: "",
    address: "",
    website: "https://cutshort.io/",
    applyUrl: "https://cutshort.io/jobs/startup-jobs-in-bangalore-bengaluru",
    email: "",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/cutshort",
    howToApproach: "Create a profile and upload your resume, then browse the Bengaluru and backend-developer job pages. Keep your skills tags (Java, Spring Boot, Node.js) precise, because invites come from AI matching.",
  },
  {
    name: "hirist.tech",
    kind: "platform",
    focus: "IT-only job portal run by Info Edge, with dedicated Java and Node.js categories and Bengaluru listings from tech-company recruiters.",
    area: "",
    address: "",
    website: "https://www.hirist.tech/",
    applyUrl: "https://www.hirist.tech/k/java-jobs",
    email: "",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/hirist-com/",
    howToApproach: "Register as a jobseeker, complete your profile and apply through the Java and Node.js category pages filtered to Bangalore. Many listings are posted by individual recruiters, so a short message with your application helps. Its published address is Info Edge's Noida office, not Bengaluru.",
  },
  {
    name: "Talent500",
    kind: "platform",
    focus: "ANSR-owned job platform focused on roles at Global Capability Centres (GCCs) in India, with AI-driven job matching.",
    area: "",
    address: "",
    website: "https://talent500.com/",
    applyUrl: "https://talent500.com/auth/signup",
    email: "",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/talent500/",
    howToApproach: "Sign up, build your profile and apply to backend and full-stack roles at Bengaluru GCCs from the jobs page. Listings are mostly at multinational captive centres, so tailor your CV to enterprise Java/Node.js work.",
  },
  {
    name: "Wellfound",
    kind: "platform",
    focus: "Startup jobs marketplace (formerly AngelList Talent) where startups and founders reach out to candidates and most listings show salary and equity; has active Bengaluru software-engineer listings.",
    area: "",
    address: "",
    website: "https://wellfound.com/",
    applyUrl: "https://wellfound.com/jobs/signup",
    email: "",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/wellfoundhq",
    howToApproach: "Create one detailed profile (it doubles as your application) and apply with one click to Bengaluru startup roles. Wellfound's AI sourcing shows your profile to matching recruiters, so keep your skills and preferences up to date, and check the salary range shown before applying.",
  },
  {
    name: "foundit (formerly Monster India)",
    kind: "platform",
    focus: "Large general job portal (formerly Monster India) with a dedicated IT/software section and Bengaluru listings.",
    area: "",
    address: "",
    website: "https://www.foundit.in/",
    applyUrl: "https://www.foundit.in/seeker/registration",
    email: "",
    phone: "+91 80 6985 7811",
    linkedinUrl: "https://www.linkedin.com/company/foundit-jobs/",
    howToApproach: "Register for free and upload your CV with clear Java/Spring Boot or Node.js keywords and Bengaluru as your preferred location so recruiters can find you. Ignore the optional paid resume services; you don't need them to apply or to be contacted.",
  },
  {
    name: "Weekday",
    kind: "platform",
    focus: "AI-powered job platform (backed by Y Combinator) that collects jobs from across the web, with Bengaluru backend-developer listings; free for candidates.",
    area: "",
    address: "",
    website: "https://www.weekday.works/",
    applyUrl: "https://jobs.weekday.works/",
    email: "",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/weekdayworks",
    howToApproach: "Sign up free on the jobs site and browse Bangalore backend and full-stack listings. It offers 'AI apply'; if you use it, check each application before it goes out. Its free resume scorer is a quick second check alongside tjob's ATS score.",
  },
  {
    name: "Y Combinator – Work at a Startup",
    kind: "platform",
    focus: "Y Combinator's job board for its startups; one free profile lets founders contact you, and some YC companies hire in Bengaluru.",
    area: "",
    address: "",
    website: "https://www.workatastartup.com/",
    applyUrl: "https://www.ycombinator.com/jobs/location/bangalore",
    email: "",
    phone: "",
    linkedinUrl: "",
    howToApproach: "Create a free profile at workatastartup.com/application; founders reach out to you, and the profile unlocks the full job list. The Bangalore page shows only some roles and few are engineering at any time, so also filter for remote roles open to India.",
  },
  {
    name: "Uplers",
    kind: "platform",
    focus: "Talent network that places Indian developers in full-time remote roles with global companies; free to join. Not Bengaluru-specific, but you can work from Bengaluru.",
    area: "",
    address: "",
    website: "https://www.uplers.com/",
    applyUrl: "https://platform.uplers.com/talent/joinus",
    email: "",
    phone: "",
    linkedinUrl: "https://www.linkedin.com/company/weareuplers",
    howToApproach: "Join the talent network free and complete its three screening tests; if you don't clear them you can reapply after 2 months. Roles are remote, 8 hours a day, 5 days a week, with a minimum 3-month contract, so read each offer's terms before accepting.",
  },
];
